### PR TITLE
Update grep regex for precise filtering of repo urls

### LINKED ISSUE #20: [Bug] failing validation check on GitHub repo slug
If source or destination repo is "https://github.com/shakti-garg/datahub", the whole script should fail as it is neither a repo slug nor full clone url.

Reason:
In git-sync.sh, the following condition is failing
```
if ! echo $SOURCE_REPO | grep '.git'
```
as grep is using a special regex character '.'

### PR DESCRIPTION
**Pull request by shakti-garg**
Fix #20

### CODE REVIEW

**Comment by wei** [comment]
Thanks for your pr. We should do the same thing as https://github.com/repo-sync/github-sync/pull/30

**Comment by shakti-garg** [comment]
Thanks for the guidance. This suggestion to include other patterns totally makes sense. I am wondering if there could be more URL patterns than listed above(always a possibility).

As another approach, instead of doing negative validation, should we do positive validation check on repo slug? For example, validating on SOURCE_REPO matching regex expressing slug pattern("^[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+$")

**Comment by wei** [comment]
The pattern listed are taken from Git documentation, I think it's safe to assume that covers 99.99% of the possibilities.

**Comment by shakti-garg** [comment]
I went ahead with the solution in repo-sync/github-sync#30 and have added commit for the same.

The other suggested solution didn't came up very nicely as i was not confident on regex for repository-name(though i was confident of regex for github user-name).

**Comment by wei** [comment]
🎉 Thanks for the PR. It can be accessed with `v2` or `v2.1.0` tags

**Pull request merged**
