### PR TITLE
feat: Update tags when syncing

### PR DESCRIPTION
**Pull request by NobodyXu**
Push new tags from source to destination

### CODE REVIEW

**Comment by wei** [comment]
Thanks for the PR, could you explain the behavior of this Git command? does it only push tags that has the same ref as SOURCE_BRANCH?

**Comment by NobodyXu** [comment]
It actually push all tags regardless of the reference.

I copied the command used to pushing branches without trimming the arguments after them because I was not sure what it did, but after researching, I found that to be useless unless modified to command to

```
git push refs/tags/<tag>:refs/tags/<tag>
```

otherwise, `git push --tags` will always update all tags.

**Comment by NobodyXu** [comment]
Actually, if user wants more control over this, then adding the following argument to `git-sync.sh` can archive this:

```
SOURCE_TAG=$5
DESTINATION_TAG=$6

git push destination ${SOURCE_TAG}:${DESTINATION_TAG}
```

However, I am not completely sure about this, so I didn't include this in my commit.

**Comment by wei** [comment]
Thanks for the quick response. After testing, users can just set 
```
SOURCE_BRANCH: "refs/tags/*"
DESTINATION_BRANCH: "refs/tags/*"
```
to push all tags from source to master.

**Comment by NobodyXu** [comment]
Thank you for taking your time reviewing my PR ^_^
Wish u have a good day

**Pull request closed without merging**
